### ISSUE TITLE
Syntax highlight broken if attribute contains ampersand 

### ISSUE THREAD

**Issue by surdu** [atom/language-html#141]
Atom: v1.12.0-beta1
language-html: v0.46.1

If an attribute contains an ampersand, the syntax highlight after that ampersand is broken.

<img width="367" alt="screen shot 2016-10-14 at 12 33 14" src="https://cloud.githubusercontent.com/assets/11520795/19382828/78266f54-920a-11e6-9066-41aeefeab608.png">

Appears to work correctly in :
Atom: v1.11.1
language-html: 0.45.1

<img width="355" alt="screen shot 2016-10-14 at 12 43 02" src="https://cloud.githubusercontent.com/assets/11520795/19383208/e5199f72-920b-11e6-91df-14150e26b350.png">

... except the ampersand error, but that appears to be covered in #116

**Comment by freijbe** [comment]
This bug is still present

**Comment by 50Wliu** [comment]
The fix is not present in that version.

**Comment by beck410** [comment]
Can confirm - bug is still present in Atom 1.12.2

**Comment by Ben3eeE** [comment]
The fix is not present in that version.

**Comment by beck410** [comment]
will it be added to this version?

**Comment by 50Wliu** [comment]
That's still under discussion.  If a decision is made, it'll be documented here.  Otherwise, expect this to be fixed in Atom 1.14.0.

**Comment by 50Wliu** [comment]
The fix is now available in Atom 1.12.5.

**Comment by adampengh** [comment]
I just upgraded to version 1.22.0 and I'm now experiencing this issue.

![screen shot 2017-11-09 at 11 49 35 am](https://user-images.githubusercontent.com/16685652/32617887-3726bd88-c544-11e7-91c3-5d70839bbc67.png)

**Comment by austin-guevara** [comment]
The issue is also present in 1.22.1.

**Comment by oskarom** [comment]
Just updated to Atom version 1.22.1, confirming the return of this issue...

**Comment by syamsoul** [comment]
1 year....the bug is still not fixed..

**Comment by Batto1300** [comment]
Experiencing the same bug here! Atom 1.22

**Comment by xlcaliburn** [comment]
Experiencing the bug for HTML as well, Atom v1.22.1

**Comment by Rickety-Cricket** [comment]
I'm having the same issue with HTML. Atom v1.22.1, OSX v10.11.6.

**Comment by 50Wliu** [comment]
I am looking into this now.

**Comment by 50Wliu** [comment]
This should be re-fixed in Atom 1.23 when it is released.  Apologies for the poor editing experience.

**Comment by per000** [comment]
This is still an issue in Atom 1.23 
![image](https://user-images.githubusercontent.com/34508823/33936569-4bcf9756-e000-11e7-9591-a343c39c2ba5.png)

**Comment by karlschwaier** [comment]
This bug seems to be still present in the following scenario:
![bildschirmfoto 2017-12-13 um 15 03 02](https://user-images.githubusercontent.com/2789472/33942711-0e9f27b8-e017-11e7-8bee-19dd3fb6cdd3.png)

**Comment by 50Wliu** [comment]
@karlschwaier Would you mind opening a new issue for that?

**Comment by Chase-Silk** [comment]
![screen shot 2018-02-12 at 1 13 00 pm](https://user-images.githubusercontent.com/18050394/36098602-720fba00-0ff7-11e8-8438-be07988c2ea6.png)
